
# SEO settings
title: "iChuot"
title2: "" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://ichuot.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-68635944-1
repo: http://github.com/ichuot
disqus_shortname: "ichuot"
twitter_username: "ichuot"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Tuấn Ngô"
  job      : "Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : ichuot@gmail.com
  url      : http://ichuot.github.io
  github   : http://github.com/ichuot
  twitter  : http://twitter.com/ichuot
  facebook : https://www.facebook.com/ichuot
  linkedin : http://linkedin.com/in/ichuot

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@ichuot"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
